### ISSUE TITLE
Create Card

### ISSUE THREAD

**Issue by adanj27** [adanj27/Web-Dev-Hut-Open-Source#19]
Buscar el archivo Card.jsx y crear un componente global.
P.D. Seguir el diseño de figma
https://www.figma.com/file/CVUWo2Up36fZrrC21cRi2J/Dise%C3%B1o-mockups?type=design&node-id=62%3A2&t=o4j73QTszOHtS7M0-1

![Image](https://user-images.githubusercontent.com/117919468/236702078-a26bc371-b019-42c3-86ca-1055a2f76f80.PNG)

**Comment by FOWMind** [comment]
The card component was implemented in commit [4c23860](https://github.com/adanj27/Web-Dev-Hut-Open-Source/pull/28/commits/4c238605e8776a6cd550f1b5e55dc467c51ee783)
Anyway, it didn't passed the linter check.

The issue was fixed with commit [58b9a5d](https://github.com/adanj27/Web-Dev-Hut-Open-Source/commit/58b9a5de58c241834c13ddbb8c71591ad4257b32) in pull request #28
